name: ridethebee
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  smooth_page_indicator: ^0.2.0
  flutter_switch: ^0.3.1
  app_settings: 4.0.1+1
  maps_launcher: ^2.0.0
  intl: ^0.17.0
  flutter_rounded_date_picker: ^2.0.2
  flutter_dash:
  dio: ^4.0.0
  fluttertoast: ^8.0.7
  device_id: ^0.2.0
  shared_preferences: ^2.0.6

  firebase_core: ^1.4.0
  firebase_core_platform_interface: ^4.0.1
  firebase_auth: ^3.0.1
  firebase_messaging: ^10.0.4

  google_maps_flutter: ^2.0.6
  flutter_plugin_android_lifecycle: ^2.0.1
  image_picker: ^0.8.3+2
  http_parser: ^4.0.0
  location_web: ^3.1.1
  location: ^4.3.0

  shimmer: ^2.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/img_splash_logo.png
    - assets/image_boarding.png
    - assets/ic_eye_open.png
    - assets/ic_facebook.png
    - assets/ic_twitter.png
    - assets/img_ride_the_bee.png
    - assets/ic_back_yellow.png
    - assets/ic_menu.png
    - assets/ic_notification.png
    - assets/img_list.png
    - assets/img_swap.png
    - assets/ic_filter.png
    - assets/img_circle_rtb.png
    - assets/ic_bus.png
    - assets/ic_close_black.png
    - assets/ic_home.png
    - assets/ic_book_trip.png
    - assets/ic_ticket_details.png
    - assets/ic_my_wallet.png
    - assets/ic_settings.png
    - assets/img_notif_example.png
    - assets/ic_three_dots.png
    - assets/ic_yellow_notification.png
    - assets/img_barcode.png
    - assets/img_boarding_1.png
    - assets/img_boarding.png
    - assets/img_baording_2.png
    - assets/ic_google_plus.png
    - assets/ic_back_black.png
    - assets/img_home_background.png
    - assets/ic_calendar.png
    - assets/ic_yellow_dropdown.png
    - assets/ic_yellow_circle.png
    - assets/ic_black_circle.png
    - assets/ic_dots.png
    - assets/ic_filter.png
    - assets/img_filter.png
    - assets/ic_track.png
    - assets/img_ridethebees.png
    - assets/ic_bus.png
    - assets/ic_triangle_arrow.png
    - assets/home_background.png
    - assets/ic_circle_right.png
    - assets/ic_graycircle_arrow.png
    - assets/ic_ongoing.png
    - assets/ic_upcoming.png
    - assets/ic_completed.png
    - assets/ic_search_trips.png
    - assets/ic_wallet.png
    - assets/img_default_profile.png
    - assets/ic_new_back_yellow.png
    - assets/ic_minus_grey.png
    - assets/ic_plus_green.png
    - assets/ic_yellow_right.png
    - assets/ic_search_white.png
    - assets/ic_yellow_check.png
    - assets/ic_debit_card.png
    - assets/ic_online_booking.png
    - assets/ic_unselected_payment.png
    - assets/ic_cashback_wallet.png
    - assets/img_successfull.png
    - assets/img_thankyou.png
    - assets/img_completed.png
    - assets/ic_black_star.png
    - assets/ic_yellow_star.png
    - assets/img_begin_trip.png
    - assets/ic_yellow_from.png
    - assets/ic_yellow_location.png
    - assets/ic_black_uparrow.png
    - assets/ic_black_circle.png
    - assets/ic_current_location.png
    - assets/ic_km.png
    - assets/ic_yellow_notif.png
    - assets/ic_yellow_message.png
    - assets/ic_black_dropdown.png
    - assets/img_alert.png
    - assets/img_share.png
    - assets/img_emergency.png
    - assets/img_reminder.png
    - assets/img_available_seat.png
    - assets/img_booked_seat.png
    - assets/img_selected_seat.png
    - assets/ic_new_travis.png
    - assets/img_seat_background.png
    - assets/ic_end_dot.png
    - assets/img_menu_background.png
    - assets/img_driver_home.png
    - assets/ic_send.png
    - assets/ic_black_left.png
    - assets/ic_white_star.png
    - assets/ic_triangleup_arrow.png
    - assets/ic_circle_down.png
    - assets/ic_circle_up.png

  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/poppins_bold.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/poppins_medium.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/poppins_regular.ttf

